CREATE TABLE IF NOT EXISTS emprunts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  utilisateur_id INT NOT NULL,
  livre_id INT NOT NULL,
  date_emprunt DATETIME DEFAULT CURRENT_TIMESTAMP,
  date_echeance DATETIME NOT NULL,
  date_retour DATETIME DEFAULT NULL,

  FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id) ON DELETE CASCADE,
  FOREIGN KEY (livre_id) REFERENCES livres(id) ON DELETE CASCADE
);
